// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frfrfzhatedurmzhzopu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZnJmemhhdGVkdXJtemh6b3B1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0NTE4MTEsImV4cCI6MjA4NjAyNzgxMX0.VskP4Aug8cbUXxPm16ZRIbaL9zoK9Zd02OzCgM97gJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});